package RecordClass;

public class RecordApp {
    public static void main(String[] args) {
        // must insert the data of the constructor
        LoginRequest loginRequest = new LoginRequest("Daniel", "Semarang");

        // not using getter and setter method, but instead use the name of the class/object first then the field name.
        System.out.println(loginRequest.username());
        System.out.println(loginRequest.password());

        System.out.println(loginRequest); // LoginRequest[username=Daniel, password=Semarang] 
        // the toString method is already generated by java, so we don't have to generate it manually. 

        // Constructor overloading
        System.out.println(new LoginRequest());
        System.out.println(new LoginRequest("Tirza"));
        System.out.println(new LoginRequest("Tirza", "Semarang"));
    }
}
       

